language: node_js

node_js:
  - 12.8.0

services:
  - docker

cache:
  directories:
    - node_modules

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t youzizi1/hook-client-pd:latest .
  - docker push youzizi1/hook-client-pd:latest
